# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20170228_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='toy',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='toy',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='toy',
            name='condition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='toy',
            name='msrp',
            field=models.IntegerField(),
        ),
    ]
